//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.19 at 07:37:16 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.unimod.org/xmlns/schema/unimod_2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package au.edu.unimelb.plantcell.servers.mascot.unimod.v2;
