//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.30 at 02:37:10 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/JobMessage", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package au.edu.unimelb.plantcell.servers.core.jaxb;
