//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.25 at 08:03:10 AM EST 
//


package au.edu.unimelb.plantcell.servers.proteowizard.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mzFilteringType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mzFilteringType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mzWindowFilter" type="{http://www.example.org/NewXMLSchema}mzWindowFilterType" minOccurs="0"/>
 *         &lt;element name="precursorFilter" type="{http://www.w3.org/2001/XMLSchema}double" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="peakListLengthFilter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mzFilteringType", propOrder = {
    "mzWindowFilter",
    "precursorFilter",
    "peakListLengthFilter"
})
public class MzFilteringType {

    protected MzWindowFilterType mzWindowFilter;
    @XmlElement(type = Double.class)
    protected List<Double> precursorFilter;
    protected String peakListLengthFilter;

    /**
     * Gets the value of the mzWindowFilter property.
     * 
     * @return
     *     possible object is
     *     {@link MzWindowFilterType }
     *     
     */
    public MzWindowFilterType getMzWindowFilter() {
        return mzWindowFilter;
    }

    /**
     * Sets the value of the mzWindowFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link MzWindowFilterType }
     *     
     */
    public void setMzWindowFilter(MzWindowFilterType value) {
        this.mzWindowFilter = value;
    }

    /**
     * Gets the value of the precursorFilter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the precursorFilter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrecursorFilter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Double }
     * 
     * 
     */
    public List<Double> getPrecursorFilter() {
        if (precursorFilter == null) {
            precursorFilter = new ArrayList<Double>();
        }
        return this.precursorFilter;
    }

    /**
     * Gets the value of the peakListLengthFilter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeakListLengthFilter() {
        return peakListLengthFilter;
    }

    /**
     * Sets the value of the peakListLengthFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeakListLengthFilter(String value) {
        this.peakListLengthFilter = value;
    }

}
