//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.25 at 08:03:10 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/NewXMLSchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package au.edu.unimelb.plantcell.servers.proteowizard.jaxb;
